/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';
import { PetPetTypeEnum, petPetTypeEnumSchema } from './petPetTypeEnum';

/** A single Pet object */
export interface Pet {
  /** a unique identifier for a Pet */
  id: bigint;
  /** the name lovingly given to the pet */
  name: string;
  /** the type of pets allowed */
  petType?: PetPetTypeEnum;
}

export const petSchema: Schema<Pet> = object({
  id: ['id', bigint()],
  name: ['name', string()],
  petType: ['petType', optional(petPetTypeEnumSchema)],
});
