/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PetPetTypeEnum
 */
export enum PetPetTypeEnum {
  Dog = 'dog',
  Cat = 'cat',
}

/**
 * Schema for PetPetTypeEnum
 */
export const petPetTypeEnumSchema: Schema<PetPetTypeEnum> = stringEnum(PetPetTypeEnum);
